version: "3.8"

services:
  app:
    container_name: telegram-uploader
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8078:8078"
    env_file:
      - .env
    volumes:
      - app-logs:/app/logs
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8078/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

volumes:
  app-logs:
